version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trading"
s3_prefix = "trading"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides = "Environment=\"dev\""
image_repositories = []
